create table reports (
    id integer primary key generated by default as identity,
    report_first text not null,
    report_last text not null,
    report_email text not null,
    report_phone text not null,
    report_lat numeric(16, 14) not null,
    report_lng numeric(16, 14) not null,
    report_date text not null,
    report_type text not null,
    report_time text,
    report_waterBody text,
    report_other text,
    report_details text,
    report_created_at TIMESTAMPTZ default now() not null
);